title = "Nicholas Shea"
baseURL = "https://www.nicholasshea.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-153497726-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/NicholasShea12"
  instagram = ""
  youtube = ""
  github = "https://github.com/nshea3"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/nicholas-shea-94b338138/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  removefromexternalsearch = false
